language: node_js
node_js:
  - node
install:
  - npm install -q --no-color --no-progress
  - npm install -g codecov
script:
  - make lint
  - make test
  - codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT